name: Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

#env:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        sudo apt update
        sudo apt install -y libusb-1.0-0-dev  libykpers-1-dev libyubikey-dev qt5-qmake qtbase5-dev
        qmake
        make

    - name: Upload
      env:
        GH_REPO: ${{ github.repository }}
        GH_TOKEN: ${{ github.token }}
      run: |
          artifacts=build/release/yubikey-personalization-gui
          tag=$(date +%Y%m%d)

          gh release create --latest ${tag} -t ${tag} ${artifacts}
